language: go
go:
  - "1.7"

git:
  depth: 10

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install node -y
  - go get -u -v github.com/spf13/hugo
  - npm install -g gulp
  - npm install -g travis-ci-cloudfront-invalidation

install:
  - npm install

script:
  - gulp sass && hugo

before_deploy:
  - gulp sass && hugo

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_PROD
    skip_cleanup: true
    local-dir: public
    on:
      branch: master

after_deploy:
  - if [[ $TRAVIS_BRANCH = "master" ]]; then travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_ID_PROD -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST; fi
